import { Product } from './types';

export const initialProducts: Product[] = [
  // --- 1. SIZ BERGAN ORIGINAL RASMLI MAHSULOTLAR (OLDINGI RO'YXAT) ---
  {
    id: "p1",
    name: "SHELL Helix HX7 10W-40",
    category: "Motor Oil",
    liters: ["1L", "4L"],
    price_uzs: [98000, 315000],
    image_url: "https://bizkim.uz/foto_product/5596_19_eiKflI4S4vVE_1.jpg",
    description: "Sintetik texnologiyali motor moyi. Dvigatelni tozalash va himoya qilish uchun maxsus ishlab chiqilgan bo'lib, loy hosil bo'lishining oldini oladi.",
    tags: ["Top Product", "Recommended"],
    seo: { title: "SHELL Helix HX7 10W-40", meta_description: "SHELL Helix HX7 10W-40 O'zbekistonda original narxda." },
    telegram_bot: { buy_button: true, status_sequence: ["Pending"], admin_notification: true, pdf_receipt: true, payment_card: "9860 1701 1369 9921", user_data_required: ["full_name", "phone_number"] } as any
  },
  {
    id: "p2",
    name: "Venol 5W-30",
    category: "Motor Oil",
    liters: ["1L", "4L"],
    price_uzs: [95000, 320000],
    image_url: "https://ir.ozone.ru/s3/multimedia-1-x/c1000/6924233157.jpg",
    description: "Yuqori sifatli sintetik motor moyi. Yoqilg'i sarfini kamaytirish va dvigatelni sovuq havoda oson ishga tushirish uchun optimallashtirilgan.",
    tags: ["Premium", "New"],
    seo: { title: "Venol 5W-30", meta_description: "Venol 5W-30 sintetik moyi narxi." },
    telegram_bot: { buy_button: true, status_sequence: ["Pending"], admin_notification: true, pdf_receipt: true, payment_card: "9860 1701 1369 9921", user_data_required: ["full_name", "phone_number"] } as any
  },
  {
    id: "p3",
    name: "CASTROL Magnatec 5W-30 A5",
    category: "Motor Oil",
    liters: ["1L", "4L"],
    price_uzs: [140000, 510000],
    image_url: "https://m.media-amazon.com/images/I/61HX9rb-a5L._AC_UF894,1000_QL80_.jpg",
    description: "DUALOCK molekulalari bilan himoyalangan. Start-Stop rejimida dvigatelni yeyilishdan 50% gacha yaxshiroq himoya qiladi.",
    tags: ["Sale"],
    seo: { title: "Castrol Magnatec 5W-30", meta_description: "Castrol Magnatec O'zbekistonda narxlari." },
    telegram_bot: { buy_button: true, status_sequence: ["Pending"], admin_notification: true, pdf_receipt: true, payment_card: "9860 1701 1369 9921", user_data_required: ["full_name", "phone_number"] } as any
  },
  {
    id: "p4",
    name: "Venol 15W-40",
    category: "Motor Oil",
    liters: ["1L", "4L", "5L"],
    price_uzs: [55000, 195000, 240000],
    image_url: "https://cdn.myshoptet.com/usr/www.hahn-profi.com/user/shop/big/10881_venol-formula-engine-oil-15w-40.jpg?630c9a10",
    description: "Universal mineral motor moyi. Katta yurgan dvigatellar uchun juda mos keladi.",
    tags: ["Economy"],
    seo: { title: "Venol 15W-40", meta_description: "Venol 15W-40 arzon va sifatli." },
    telegram_bot: { buy_button: true, status_sequence: ["Pending"], admin_notification: true, pdf_receipt: true, payment_card: "9860 1701 1369 9921", user_data_required: ["full_name", "phone_number"] } as any
  },
  {
    id: "p5",
    name: "ZIC X9 5W-40",
    category: "Motor Oil",
    liters: ["1L", "4L"],
    price_uzs: [115000, 390000],
    image_url: "https://devel.prom.uz/upload/products/39/8e/398e5f3193d6738ab167633e9c6b4b12.jpg",
    description: "VHVI texnologiyasi asosida ishlab chiqarilgan 100% sintetik motor moyi. Dvigatelning xizmat muddatini uzaytiradi.",
    tags: ["Top Product"],
    seo: { title: "ZIC X9 5W-40", meta_description: "ZIC X9 5W-40 Toshkentda narxi." },
    telegram_bot: { buy_button: true, status_sequence: ["Pending"], admin_notification: true, pdf_receipt: true, payment_card: "9860 1701 1369 9921", user_data_required: ["full_name", "phone_number"] } as any
  },
  {
    id: "p6",
    name: "Fortex HD 46",
    category: "Hydraulic Oil",
    liters: ["20L", "50L"],
    price_uzs: [450000, 1100000],
    image_url: "https://fortex.uz/wp-content/uploads/2021/05/hd-46.png",
    description: "Sanoat va og'ir texnikalar gidravlika tizimlari uchun maxsus ishlab chiqarilgan moy.",
    tags: ["Industrial"],
    seo: { title: "Fortex HD 46", meta_description: "Fortex HD 46 gidravlika moyi." },
    telegram_bot: { buy_button: true, status_sequence: ["Pending"], admin_notification: true, pdf_receipt: true, payment_card: "9860 1701 1369 9921", user_data_required: ["full_name", "phone_number"] } as any
  },
  {
    id: "p7",
    name: "Fortex Diesel 15W-40",
    category: "Motor Oil",
    liters: ["5L", "20L"],
    price_uzs: [180000, 680000],
    image_url: "https://fortex.uz/wp-content/uploads/2021/04/diesel-15-w-40.png",
    description: "Og'ir yuk mashinalari va traktorlar uchun maxsus dizel motor moyi. Barcha mavsumlarda ishonchli himoya.",
    tags: ["Diesel"],
    seo: { title: "Fortex Diesel 15W-40", meta_description: "Yuk mashinalari uchun motor moyi." },
    telegram_bot: { buy_button: true, status_sequence: ["Pending"], admin_notification: true, pdf_receipt: true, payment_card: "9860 1701 1369 9921", user_data_required: ["full_name", "phone_number"] } as any
  },
  {
    id: "p8",
    name: "Fortex SAE 10W-40",
    category: "Motor Oil",
    liters: ["1L", "4L", "5L"],
    price_uzs: [45000, 160000, 195000],
    image_url: "https://fortex.uz/wp-content/uploads/2021/04/2132131-1024x810.png",
    description: "Universal yarim sintetik motor moyi. Barcha turdagi yengil avtomobillar uchun mos keladi.",
    tags: ["Local"],
    seo: { title: "Fortex SAE 10W-40", meta_description: "Mahalliy iqlim uchun moslashtirilgan Fortex." },
    telegram_bot: { buy_button: true, status_sequence: ["Pending"], admin_notification: true, pdf_receipt: true, payment_card: "9860 1701 1369 9921", user_data_required: ["full_name", "phone_number"] } as any
  },
  {
    id: "p9",
    name: "LiQui Moly 5W-30",
    category: "Motor Oil",
    liters: ["1L", "5L"],
    price_uzs: [175000, 780000],
    image_url: "https://cdn.opieoils.co.uk/images/variants/large/liquimoly/liqui-moly-molygen-new-generation-5w-30-engine-oil-5litres-9952-1.jpg",
    description: "Molygen New Generation - noyob texnologiya. Dvigatelni ishqalanishdan mukammal himoya qiladi va yoqilg'ini tejaydi. (Yashil rangli)",
    tags: ["Premium"],
    seo: { title: "LiQui Moly 5W-30", meta_description: "LiQui Moly Molygen 5W-30 narxi." },
    telegram_bot: { buy_button: true, status_sequence: ["Pending"], admin_notification: true, pdf_receipt: true, payment_card: "9860 1701 1369 9921", user_data_required: ["full_name", "phone_number"] } as any
  },
  {
    id: "p10",
    name: "LiQui Moly 5W-40",
    category: "Motor Oil",
    liters: ["1L", "5L"],
    price_uzs: [170000, 750000],
    image_url: "https://n75motorsports.ca/cdn/shop/products/msedge_mpByDKHJwn_1200x1200.png?v=1609488544",
    description: "Leichtlauf High Tech 5W-40. Zamonaviy benzin va dizel dvigatellari uchun butun mavsumli, gidrokreking texnologiyali sintetik moy.",
    tags: ["Top Tier"],
    seo: { title: "LiQui Moly 5W-40", meta_description: "LiQui Moly 5W-40 Leichtlauf narxi." },
    telegram_bot: { buy_button: true, status_sequence: ["Pending"], admin_notification: true, pdf_receipt: true, payment_card: "9860 1701 1369 9921", user_data_required: ["full_name", "phone_number"] } as any
  },
  {
    id: "p11",
    name: "Lukoil 5W-30",
    category: "Motor Oil",
    liters: ["1L", "4L"],
    price_uzs: [80000, 290000],
    image_url: "https://ir.ozone.ru/s3/multimedia-1-1/c1000/6984769249.jpg",
    description: "Lukoil Genesis Armortech. Zamonaviy avtomobillar uchun sintetik moy.",
    tags: ["Popular"],
    seo: { title: "Lukoil Genesis 5W-30", meta_description: "Lukoil Genesis 5W-30 narxlari." },
    telegram_bot: { buy_button: true, status_sequence: ["Pending"], admin_notification: true, pdf_receipt: true, payment_card: "9860 1701 1369 9921", user_data_required: ["full_name", "phone_number"] } as any
  },
  {
    id: "p12",
    name: "Lukoil Genesis 10W-40",
    category: "Motor Oil",
    liters: ["1L", "4L", "5L"],
    price_uzs: [65000, 230000, 280000],
    image_url: "https://www.mvh-shop.de/media/image/product/476127/lg/car-engine-oil-lukoil-genesis-advanced-56304050-sae-10w-40-5-liters-oil-filter-sh-422-p~3.jpg",
    description: "Lukoil Genesis Advanced. Og'ir sharoitlarda ishlaydigan dvigatellar uchun yuqori sifatli yarim sintetik moy.",
    tags: ["Best Seller"],
    seo: { title: "Lukoil 10W-40 Advanced", meta_description: "Lukoil 10W-40 yarim sintetik." },
    telegram_bot: { buy_button: true, status_sequence: ["Pending"], admin_notification: true, pdf_receipt: true, payment_card: "9860 1701 1369 9921", user_data_required: ["full_name", "phone_number"] } as any
  },
  {
    id: "p13",
    name: "Lukoil 5W-40",
    category: "Motor Oil",
    liters: ["1L", "4L"],
    price_uzs: [85000, 310000],
    image_url: "https://ir.ozone.ru/s3/multimedia-1-x/c600/6984767517.jpg",
    description: "Lukoil Genesis Armortech 5W-40. Barcha fasllar uchun mo'ljallangan to'liq sintetik moy.",
    tags: [],
    seo: { title: "Lukoil 5W-40 Sintetik", meta_description: "Lukoil Armortech 5W-40." },
    telegram_bot: { buy_button: true, status_sequence: ["Pending"], admin_notification: true, pdf_receipt: true, payment_card: "9860 1701 1369 9921", user_data_required: ["full_name", "phone_number"] } as any
  },
  {
    id: "p14",
    name: "Enoc 5W-30",
    category: "Motor Oil",
    liters: ["1L", "4L"],
    price_uzs: [90000, 340000],
    image_url: "https://olcha.uz/image/700x700/products//supplier/stores/26957/olcha%2F6.jpg",
    description: "BAA texnologiyasi asosida ishlab chiqarilgan yuqori sifatli moy. Issiq iqlim uchun mos.",
    tags: ["New", "Hot Climate"],
    seo: { title: "Enoc 5W-30", meta_description: "Enoc moylari O'zbekistonda." },
    telegram_bot: { buy_button: true, status_sequence: ["Pending"], admin_notification: true, pdf_receipt: true, payment_card: "9860 1701 1369 9921", user_data_required: ["full_name", "phone_number"] } as any
  },

  // --- 2. YANGILANGAN VA QO'SHIMCHA MAHSULOTLAR (FORTEX & BOSHQA) ---
  {
    id: "p15",
    name: "SHELL Helix Ultra 5W-40",
    category: "Motor Oil",
    liters: ["1L", "4L"],
    price_uzs: [110000, 395000],
    image_url: "https://www.shell.com.au/motorists/oils-lubricants/helix-for-cars/helix-fully-synthetic/shell-helix-ultra-5w-40/_jcr_content/root/main/section/standalone_asset.shellimg.jpeg/1694705917173/helix-ultra-sp-5w40-5l-front-one.jpeg?imwidth=301&impolicy=amidala-image&imdensity=1",
    description: "Shell PurePlus gazdan-suyuqlik texnologiyasi. Dvigatelni tozalash va himoya qilishda eng yuqori standartlarni ta'minlovchi to'liq sintetik moy.",
    tags: ["Premium"],
    seo: { title: "Shell Helix Ultra 5W-40", meta_description: "Shell Ultra 5W-40 sintetik narxi." },
    telegram_bot: { buy_button: true, status_sequence: ["Pending"], admin_notification: true, pdf_receipt: true, payment_card: "9860 1701 1369 9921", user_data_required: ["full_name", "phone_number"] } as any
  },
  {
    id: "p16",
    name: "Fosser GAS 10W-40",
    category: "Motor Oil",
    liters: ["1L", "4L"],
    price_uzs: [60000, 220000],
    image_url: "https://olcha.uz/image/700x700/products/cdn_1/supplier/stores/1/2024-07-19/DrPYAPELj0NxCq4Jxd1XwNshGaEYFJuSISOJWyL8NJ9mvrkN7FbWzm81akl8.jpg",
    description: "Gaz (LPG/CNG) da yuradigan avtomobillar uchun maxsus ishlab chiqarilgan Germaniya sifati. Dvigatelni qizib ketishdan saqlaydi.",
    tags: ["LPG Optimized", "German Tech"],
    seo: { title: "Fosser GAS 10W-40", meta_description: "Gazli mashinalar uchun Fosser moyi." },
    telegram_bot: { buy_button: true, status_sequence: ["Pending"], admin_notification: true, pdf_receipt: true, payment_card: "9860 1701 1369 9921", user_data_required: ["full_name", "phone_number"] } as any
  },
  {
    id: "p17",
    name: "Fortex ULTRA 5W-40",
    category: "Motor Oil",
    liters: ["1L", "4L"],
    price_uzs: [55000, 180000],
    image_url: "https://fortex.uz/wp-content/uploads/2021/04/FORTEX-ULTRA-5W-40.png",
    description: "Fortex brendining eng yuqori sifatli sintetik moylaridan biri. Zamonaviy dvigatellar uchun mukammal himoya.",
    tags: ["Local Premium", "Best Seller"],
    seo: { title: "Fortex ULTRA 5W-40", meta_description: "Fortex 5W-40 sintetik moyi." },
    telegram_bot: { buy_button: true, status_sequence: ["Pending"], admin_notification: true, pdf_receipt: true, payment_card: "9860 1701 1369 9921", user_data_required: ["full_name", "phone_number"] } as any
  },
  {
    id: "p18",
    name: "Fortex 15W-40",
    category: "Motor Oil",
    liters: ["1L", "4L", "5L"],
    price_uzs: [40000, 140000, 175000],
    image_url: "https://fortex.uz/wp-content/uploads/2021/04/ENGINE-OIL-15W-40.png",
    description: "Og'ir sharoitlarda ishlaydigan va katta yurgan dvigatellar uchun sifatli mineral moy. Moy yeyilishini kamaytiradi.",
    tags: ["Heavy Duty"],
    seo: { title: "Fortex 15W-40 Mineral", meta_description: "Fortex 15W-40 mineral moyi." },
    telegram_bot: { buy_button: true, status_sequence: ["Pending"], admin_notification: true, pdf_receipt: true, payment_card: "9860 1701 1369 9921", user_data_required: ["full_name", "phone_number"] } as any
  },
  {
    id: "p19",
    name: "Shell Helix Ultra 5W-30",
    category: "Motor Oil",
    liters: ["1L", "4L"],
    price_uzs: [110000, 395000],
    image_url: "https://lkqmedia.eurocarparts.com/product/521772241/?guid=ztc6puxzh91kb9hnn3wxfkwb5kctwz6cupjugpy&currentVersion=1728482487000",
    description: "Shell PurePlus texnologiyasi. To'liq sintetik motor moyi, dvigatel tozaligi va himoyasi uchun eng yaxshi tanlov.",
    tags: ["Premium", "Fuel Economy"],
    seo: { title: "Shell Helix Ultra 5W-30", meta_description: "Shell 5W-30 motor moyi narxi." },
    telegram_bot: { buy_button: true, status_sequence: ["Pending"], admin_notification: true, pdf_receipt: true, payment_card: "9860 1701 1369 9921", user_data_required: ["full_name", "phone_number"] } as any
  },
  {
    id: "p20",
    name: "Venol Motor Moylari",
    category: "Motor Oil",
    liters: ["1L", "4L"],
    price_uzs: [55000, 200000],
    image_url: "https://mir-s3-cdn-cf.behance.net/projects/404/1b09e5183068075.Y3JvcCwyMTY5LDE2OTcsMCww.png",
    description: "Germaniyaning Venol brendidan barcha turdagi yuqori sifatli motor moylari. Keng assortiment (Barchasidan bor).",
    tags: ["Wide Range", "German Tech"],
    seo: { title: "Venol Moylari Assortimenti", meta_description: "Venol motor moylari O'zbekistonda." },
    telegram_bot: { buy_button: true, status_sequence: ["Pending"], admin_notification: true, pdf_receipt: true, payment_card: "9860 1701 1369 9921", user_data_required: ["full_name", "phone_number"] } as any
  },
  {
    id: "p21",
    name: "Felix Carbox G12+",
    category: "Antifreeze",
    liters: ["1L", "5L"],

    price_uzs: [30000, 140000],
    image_url: "https://images.uzum.uz/cf1qlqol08k0o9qhplr0/original.jpg",
    description: "Professional antifriz G12+. -40C dan +110C gacha. Qizil rangli. Alyuminiy radiatorlar uchun xavfsiz.",
    tags: ["Season"],
    seo: { title: "Felix Antifriz G12+", meta_description: "Felix qizil antifriz." },
    telegram_bot: { buy_button: true, status_sequence: ["Pending"], admin_notification: true, pdf_receipt: true, payment_card: "9860 1701 1369 9921", user_data_required: [] } as any
  },
  {
    id: "p22",
    name: "Red Antifreeze G12 (Fortex)",
    category: "Antifreeze",
    liters: ["1L", "5L"],
    price_uzs: [15000, 50000],
    image_url: "https://fortex.uz/wp-content/uploads/2021/04/002-300x300.png",
    description: "Radiator uchun yuqori sifatli qizil antifriz. Qaynash va muzlashdan ishonchli himoya qiladi.",
    tags: ["Local", "Best Price"],
    seo: { title: "Red Antifreeze G12", meta_description: "Fortex qizil antifriz." },
    telegram_bot: { buy_button: true, status_sequence: ["Pending"], admin_notification: true, pdf_receipt: true, payment_card: "9860 1701 1369 9921", user_data_required: [] } as any
  },
  {
    id: "p23",
    name: "LiQui Moly Moylari",
    category: "Motor Oil",
    liters: ["1L", "4L", "5L"],
    price_uzs: [120000, 450000, 550000],
    image_url: "https://www.tyrepress.com/wp-content/uploads/2018/07/Motorenoele2017.jpg",
    description: "Germaniyaning LiQui Moly brendi. Barcha turdagi dvigatellar uchun keng assortiment mavjud (Barchasidan bor).",
    tags: ["Wide Range", "Top Tier"],
    seo: { title: "LiQui Moly Assortiment", meta_description: "LiQui Moly moylari barcha turdagi." },
    telegram_bot: { buy_button: true, status_sequence: ["Pending"], admin_notification: true, pdf_receipt: true, payment_card: "9860 1701 1369 9921", user_data_required: [] } as any
  },
  {
    id: "p24",
    name: "Enoc Moylari",
    category: "Motor Oil",
    liters: ["1L", "4L", "20L"],
    price_uzs: [95000, 360000, 1500000],
    image_url: "https://media.licdn.com/dms/image/v2/D5622AQHMivkRQk3BDw/feedshare-shrink_800/feedshare-shrink_800/0/1699847681735?e=2147483647&v=beta&t=Dq8F8LpeWsTsCa3PJZlCF5IcSkv1BVnLGYf7a7Nx8lg",
    description: "BAA (Dubay) texnologiyasi asosida ishlab chiqarilgan yuqori sifatli Enoc moylari. Barcha turdagi dvigatellar uchun keng assortiment (Barchasidan bor).",
    tags: ["Premium", "Wide Range"],
    seo: { title: "Enoc Moylari", meta_description: "Enoc motor moylari O'zbekistonda." },
    telegram_bot: { buy_button: true, status_sequence: ["Pending"], admin_notification: true, pdf_receipt: true, payment_card: "9860 1701 1369 9921", user_data_required: [] } as any
  },
  {
    id: "p25",
    name: "Fosser Moylari",
    category: "Motor Oil",
    liters: ["1L", "4L", "5L"],
    price_uzs: [75000, 280000, 340000],
    image_url: "https://fosser.ae/wp-content/uploads/2016/01/fossermotoroil.png",
    description: "Germaniyaning Fosser brendidan barcha turdagi yuqori sifatli motor va transmissiya moylari. Nemis sifati (Barchasidan bor).",
    tags: ["German Tech", "Wide Range"],
    seo: { title: "Fosser Moylari", meta_description: "Fosser Germaniya moylari." },
    telegram_bot: { buy_button: true, status_sequence: ["Pending"], admin_notification: true, pdf_receipt: true, payment_card: "9860 1701 1369 9921", user_data_required: [] } as any
  },

  // --- 3. FORTEX BRAND & MAXSUS MAHSULOTLAR (YANGI TARJIMA QILINGAN) ---
  {
    id: "p26",
    name: "Fortex Diesel 20W-50",
    category: "Motor Oil",
    liters: ["5L", "10L", "20L"],
    price_uzs: [160000, 310000, 600000],
    image_url: "https://fortex.uz/wp-content/uploads/2021/04/diesel-15-w-40.png",
    description: "Og'ir yuk mashinalari va qishloq xo'jaligi texnikalari uchun barcha mavsumiy motor moyi.",
    tags: ["Diesel", "Heavy Duty"],
    seo: { title: "Fortex Diesel 20W-50", meta_description: "Fortex 20W-50 dizel moyi." },
    telegram_bot: { buy_button: true, status_sequence: ["Pending"], admin_notification: true, pdf_receipt: true, payment_card: "9860 1701 1369 9921", user_data_required: [] } as any
  },
  {
    id: "p27",
    name: "Fortex Engine Oil 15W-40",
    category: "Motor Oil",
    liters: ["1L", "4L", "5L"],
    price_uzs: [45000, 150000, 185000],
    image_url: "https://fortex.uz/wp-content/uploads/2021/04/ENGINE-OIL-15W-40.png",
    description: "Yengil va yuk avtomobillari uchun universal motor moyi. Dvigatelni toza saqlaydi va himoya qiladi.",
    tags: ["Universal"],
    seo: { title: "Fortex Engine Oil 15W-40", meta_description: "Universal motor moyi 15W-40." },
    telegram_bot: { buy_button: true, status_sequence: ["Pending"], admin_notification: true, pdf_receipt: true, payment_card: "9860 1701 1369 9921", user_data_required: [] } as any
  },
  {
    id: "p28",
    name: "Fortex Optima 10W-30",
    category: "Motor Oil",
    liters: ["1L", "4L"],
    price_uzs: [50000, 170000],
    image_url: "https://fortex.uz/wp-content/uploads/2021/04/FORTEX-ULTRA-5W-40.png",
    description: "Yengil va yuk mashinalari uchun sifatli yarim sintetik motor moyi. Yoqilg'i tejamkorligini ta'minlaydi.",
    tags: ["Semi-Synthetic"],
    seo: { title: "Fortex Optima 10W-30", meta_description: "Fortex Optima 10W-30 moyi." },
    telegram_bot: { buy_button: true, status_sequence: ["Pending"], admin_notification: true, pdf_receipt: true, payment_card: "9860 1701 1369 9921", user_data_required: [] } as any
  },
  {
    id: "p29",
    name: "Fortex SHPD Plus 15W-40",
    category: "Motor Oil",
    liters: ["5L", "20L", "205L"],
    price_uzs: [190000, 720000, 6800000],
    image_url: "https://fortex.uz/wp-content/uploads/2021/04/diesel-15-w-40.png",
    description: "Yuqori yuklamada ishlaydigan zamonaviy dizel dvigatellari uchun kuchaytirilgan (Super High Performance Diesel) moy.",
    tags: ["SHPD", "Heavy Duty"],
    seo: { title: "Fortex SHPD Plus 15W-40", meta_description: "Kuchaytirilgan dizel moyi." },
    telegram_bot: { buy_button: true, status_sequence: ["Pending"], admin_notification: true, pdf_receipt: true, payment_card: "9860 1701 1369 9921", user_data_required: [] } as any
  },
  {
    id: "p30",
    name: "Fortex Leader TD 10W-40",
    category: "Motor Oil",
    liters: ["4L", "5L", "20L"],
    price_uzs: [165000, 200000, 750000],
    image_url: "https://fortex.uz/wp-content/uploads/2021/04/2132131-1024x810.png",
    description: "Turbodizel va oddiy dizel dvigatellar uchun yuqori sifatli yarim sintetik moy. Sovuqda oson o't oldirishni ta'minlaydi.",
    tags: ["Turbo Diesel"],
    seo: { title: "Fortex Leader TD 10W-40", meta_description: "Turbodizel uchun moy Fortex." },
    telegram_bot: { buy_button: true, status_sequence: ["Pending"], admin_notification: true, pdf_receipt: true, payment_card: "9860 1701 1369 9921", user_data_required: [] } as any
  },
  {
    id: "p31",
    name: "Fortex Premium Diesel 10W-40",
    category: "Motor Oil",
    liters: ["5L", "20L"],
    price_uzs: [210000, 780000],
    image_url: "https://fortex.uz/wp-content/uploads/2021/04/diesel-15-w-40.png",
    description: "Yevropa standartlariga javob beruvchi, zamonaviy dizel dvigatellari uchun premium klassdagi moy.",
    tags: ["Premium", "Diesel"],
    seo: { title: "Fortex Premium Diesel", meta_description: "Premium dizel moyi." },
    telegram_bot: { buy_button: true, status_sequence: ["Pending"], admin_notification: true, pdf_receipt: true, payment_card: "9860 1701 1369 9921", user_data_required: [] } as any
  },
  {
    id: "p32",
    name: "Fortex SAE-30",
    category: "Motor Oil",
    liters: ["1L", "5L", "20L"],
    price_uzs: [35000, 150000, 550000],
    image_url: "https://fortex.uz/wp-content/uploads/2021/04/ENGINE-OIL-15W-40.png",
    description: "Bir mavsumli yozgi motor moyi. Oddiy va eskirgan dvigatellar uchun iqtisodiy yechim.",
    tags: ["Monograde", "Summer"],
    seo: { title: "Fortex SAE-30", meta_description: "SAE-30 yozgi moy." },
    telegram_bot: { buy_button: true, status_sequence: ["Pending"], admin_notification: true, pdf_receipt: true, payment_card: "9860 1701 1369 9921", user_data_required: [] } as any
  },
  {
    id: "p33",
    name: "Fortex SAE-40",
    category: "Motor Oil",
    liters: ["1L", "5L", "20L"],
    price_uzs: [38000, 160000, 580000],
    image_url: "https://fortex.uz/wp-content/uploads/2021/04/ENGINE-OIL-15W-40.png",
    description: "Issiq iqlim sharoitlari va yuqori haroratda ishlaydigan dvigatellar uchun bir mavsumli motor moyi.",
    tags: ["Monograde", "Heavy Duty"],
    seo: { title: "Fortex SAE-40", meta_description: "SAE-40 motor moyi." },
    telegram_bot: { buy_button: true, status_sequence: ["Pending"], admin_notification: true, pdf_receipt: true, payment_card: "9860 1701 1369 9921", user_data_required: [] } as any
  },
  {
    id: "p34",
    name: "Fortex SAE-50",
    category: "Motor Oil",
    liters: ["5L", "20L"],
    price_uzs: [170000, 620000],
    image_url: "https://fortex.uz/wp-content/uploads/2021/04/ENGINE-OIL-15W-40.png",
    description: "Yuqori yopishqoqlikka ega bir mavsumli motor moyi. Moy bosimi pasaygan eski dvigatellar uchun tavsiya etiladi.",
    tags: ["Monograde", "High Viscosity"],
    seo: { title: "Fortex SAE-50", meta_description: "SAE-50 quyuq moy." },
    telegram_bot: { buy_button: true, status_sequence: ["Pending"], admin_notification: true, pdf_receipt: true, payment_card: "9860 1701 1369 9921", user_data_required: [] } as any
  },
  {
    id: "p35",
    name: "Fortex SHPD 15W-40",
    category: "Motor Oil",
    liters: ["20L", "205L"],
    price_uzs: [700000, 6500000],
    image_url: "https://fortex.uz/wp-content/uploads/2021/04/diesel-15-w-40.png",
    description: "Uzoq masofaga qatnovchi yuk mashinalari va avtobuslar uchun maxsus (SHPD) motor moyi.",
    tags: ["SHPD", "Long Haul"],
    seo: { title: "Fortex SHPD 15W-40", meta_description: "Yuk mashinalari uchun SHPD moyi." },
    telegram_bot: { buy_button: true, status_sequence: ["Pending"], admin_notification: true, pdf_receipt: true, payment_card: "9860 1701 1369 9921", user_data_required: [] } as any
  },
  {
    id: "p36",
    name: "Fortex SHPD 20W-50",
    category: "Motor Oil",
    liters: ["20L", "205L"],
    price_uzs: [720000, 6700000],
    image_url: "https://fortex.uz/wp-content/uploads/2021/04/diesel-15-w-40.png",
    description: "Juda og'ir sharoitlarda va issiq iqlimda ishlaydigan maxsus texnikalar uchun yuqori samarali moy.",
    tags: ["SHPD", "Extreme Duty"],
    seo: { title: "Fortex SHPD 20W-50", meta_description: "Og'ir texnika uchun moy." },
    telegram_bot: { buy_button: true, status_sequence: ["Pending"], admin_notification: true, pdf_receipt: true, payment_card: "9860 1701 1369 9921", user_data_required: [] } as any
  },
  {
    id: "p37",
    name: "Lukoil Moylari",
    category: "Motor Oil",
    liters: ["1L", "4L", "5L", "205L"],
    price_uzs: [65000, 240000, 290000, 8500000],
    image_url: "https://rogtecmagazine.com/wp-content/uploads/2020/02/Lukoil-Barrels-2.jpg",
    description: "Lukoil kompaniyasining barcha turdagi motor va industrial moylari. Genesis, Super, Avantgarde seriyalari mavjud (Barchasidan bor).",
    tags: ["Popular", "Wide Range"],
    seo: { title: "Lukoil Moylari Assortiment", meta_description: "Lukoil moylari ulgurji va chakana." },
    telegram_bot: { buy_button: true, status_sequence: ["Pending"], admin_notification: true, pdf_receipt: true, payment_card: "9860 1701 1369 9921", user_data_required: [] } as any
  },
  {
    id: "p38",
    name: "SHELL Helix Ultra 0W-20",
    category: "Motor Oil",
    liters: ["1L", "4L"],
    price_uzs: [130000, 480000],
    image_url: "https://www.shell-livedocs.com/data/published/en-US/9036c1e5-1a3b-4177-ad6b-804155b40d6e.jpeg",
    description: "Eng zamonaviy dvigatellar uchun maxsus 0W-20 sintetik moy. Gibrid va turbo dvigatellar uchun ideal.",
    tags: ["Premium", "Hybrid"],
    seo: { title: "Shell Helix Ultra 0W-20", meta_description: "Shell 0W-20 sintetik moyi narxi." },
    telegram_bot: { buy_button: true, status_sequence: ["Pending"], admin_notification: true, pdf_receipt: true, payment_card: "9860 1701 1369 9921", user_data_required: ["full_name", "phone_number"] } as any
  },
  {
    id: "p39",
    name: "ZIC Zero 0W-20",
    category: "Motor Oil",
    liters: ["1L", "4L"],
    price_uzs: [120000, 420000],
    image_url: "https://zicoil.ru/upload/iblock/6d0/6d080f58557342738981446755675555.png",
    description: "To'liq sintetik 0W-20 motor moyi. Yoqilg'ini tejash va dvigatelni himoyalash uchun mukammal yechim.",
    tags: ["Premium", "Eco"],
    seo: { title: "ZIC Zero 0W-20", meta_description: "ZIC 0W-20 narxlari." },
    telegram_bot: { buy_button: true, status_sequence: ["Pending"], admin_notification: true, pdf_receipt: true, payment_card: "9860 1701 1369 9921", user_data_required: ["full_name", "phone_number"] } as any
  }
];